name: IaC
description: Deploy necessary resources in GCP Cloud using pulumi

inputs:
  google-application-credentials:
    required: true
    type: string
  gcp-project-id:
    required: true
    type: string
  pulumi-stack:
    required: true
    type: string
  instance-name:
    required: true
    type: string
  database-name:
    required: true
    type: string
  schema-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google 🔑
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: ${{ inputs.google-application-credentials }}

    - id: secret
      uses: google-github-actions/get-secretmanager-secrets@v2
      with:
        secrets: |
          PASSWORD:projects/${{ inputs.gcp-project-id }}/secrets/${{ inputs.pulumi-stack }}-sql-user-password-secret/versions/latest

    - name: Encode password for DATABASE_URL
      id: encode
      shell: bash
      run: |
        echo "ENCODED_PASSWORD=$(node -p 'encodeURIComponent(process.env.PASSWORD)')" >> $GITHUB_OUTPUT
      env:
        PASSWORD: ${{ steps.secret.outputs.PASSWORD }}

    - name: Download SQL Auth Proxy
      shell: bash
      run: "wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.16.0/cloud-sql-proxy.linux.amd64 -O cloud_sql_proxy"

    - name: Make the Cloud SQL Auth proxy executable
      shell: bash
      run: "chmod +x cloud_sql_proxy"

    - name: Prints instance
      shell: bash
      run: echo "$INSTANCE"
      env:
        INSTANCE: ${{ inputs.instance-name }}

    - name: Start the Cloud SQL proxy
      shell: bash
      run: ./cloud_sql_proxy $INSTANCE & sleep 5
      env:
        INSTANCE: ${{ inputs.instance-name }}

    - name: Run migration
      shell: bash
      run: "npx prisma migrate deploy"
      env:
        DATABASE_URL: "postgresql://${{ inputs.pulumi-stack }}-user:${{ steps.encode.outputs.ENCODED_PASSWORD }}@127.0.0.1:5432/${{ inputs.database-name }}?schema=${{ inputs.schema-name }}"
