name: IaC
description: Deploy necessary resources in GCP Cloud using pulumi

inputs:
  GOOGLE_APPLICATION_CREDENTIALS:
    type: string
    required: true
  PULUMI_CONFIG_PASSPHRASE:
    type: string
    required: true
  PROJECT_ID:
    type: string
    required: true
  GCP_REGION:
    type: string
    required: true
  PULUMI_STACK:
    type: string
    required: true
  CLOUD_URL:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Setup Node LTS ✨
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: npm

    - name: Installing dependencies 📦️
      run: npm install
      working-directory: iac
      shell: bash

    - name: Authenticate with Google 🔑
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: ${{ inputs.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Setup SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev
      env:
        REGION: ${{ inputs.GCP_REGION }}
      shell: bash

    - name: Preview infrastructure 🔎
      uses: pulumi/actions@v4
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.PULUMI_CONFIG_PASSPHRASE }}
      with:
        command: preview
        stack-name: ${{ inputs.PULUMI_STACK }}
        cloud-url: ${{ inputs.CLOUD_URL }}
        work-dir: iac

    - name: Up infrastructure 🚀
      uses: pulumi/actions@v4
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.PULUMI_CONFIG_PASSPHRASE }}
      with:
        command: up
        stack-name: ${{ inputs.PULUMI_STACK }}
        cloud-url: ${{ inputs.CLOUD_URL }}
        work-dir: iac