name: IaC
description: Deploy necessary resources in GCP Cloud using pulumi

inputs:
  google-application-credentials:
    type: string
    required: true
  pulumi-password:
    type: string
    required: true
  gcp-project-id:
    type: string
    required: true
  gcp-region:
    type: string
    required: true
  pulumi-stack:
    type: string
    required: true
  pulumi-login-url:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9.13.2

    - name: Setup Node LTS ✨
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm

    - name: Installing dependencies 📦️
      run: npm pkg delete scripts.prepare && pnpm install --frozen-lockfile
      working-directory: iac
      shell: bash

    - name: Authenticate with Google 🔑
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: ${{ inputs.google-application-credentials }}

    - name: Setup SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.gcp-project-id }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev
      env:
        REGION: ${{ inputs.gcp-region }}
      shell: bash

    - name: Preview infrastructure 🔎
      uses: pulumi/actions@v4
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.pulumi-password }}
      with:
        command: preview
        stack-name: ${{ inputs.pulumi-stack }}
        cloud-url: ${{ inputs.pulumi-login-url }}
        work-dir: iac

    - name: Up infrastructure 🚀
      uses: pulumi/actions@v4
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.pulumi-password }}
      with:
        command: up
        stack-name: ${{ inputs.pulumi-stack }}
        cloud-url: ${{ inputs.pulumi-login-url }}
        work-dir: iac