name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.13.2
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: npm pkg delete scripts.prepare && pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build

      - name: "IaC"
        uses: ./.github/actions/iac
        with:
          google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          pulumi-password: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          pulumi-stack: ${{ vars.PULUMI_STACK }}
          pulumi-login-url: ${{ vars.CLOUD_URL }}
          gcp-project-id: ${{ vars.PROJECT_ID }}
          gcp-region: ${{ vars.GCP_REGION }}

      - name: "migrate"
        uses: ./.github/actions/migrate
        with:
          google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          gcp-project-id: ${{ vars.PROJECT_ID }}
          pulumi-stack: ${{ vars.PULUMI_STACK }}
          instance-name: ${{ vars.INSTANCE_NAME }}
          database-name: ${{ vars.DATABASE_NAME }}
          schema-name: ${{ vars.SCHEMA_NAME }}

      - name: "docker-build"
        uses: ./.github/actions/docker
        with:
          image-name: api
          google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          gcp-project-id: ${{ vars.PROJECT_ID }}
          gcp-region: ${{ vars.GCP_REGION }}
          pulumi-stack: ${{ vars.PULUMI_STACK }}
