name: IaC
description: Deploy necessary resources in GCP Cloud using pulumi
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true
      PULUMI_CONFIG_PASSPHRASE:
        required: true
jobs:
  filter-iac:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      iac: ${{ steps.filter.outputs.iac }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            iac:
              - 'iac/**'
              - '.github/workflows/iac.yml'
  preview-and-up:
    needs: [filter-iac]
    if: needs.filter-iac.outputs.iac == 'true'
    name: Preview and Up resources
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Installing dependencies 📦️
        run: npm install
        working-directory: iac

      - name: Authenticate with Google 🔑
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev
        env:
          REGION: ${{ vars.GCP_REGION }}

      - name: Preview infrastructure 🔎
        uses: pulumi/actions@v4
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        with:
          command: preview
          stack-name: ${{ vars.PULUMI_STACK }}
          cloud-url: ${{ vars.CLOUD_URL }}
          work-dir: iac

      - name: Up infrastructure 🚀
        uses: pulumi/actions@v4
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        with:
          command: up
          stack-name: ${{ vars.PULUMI_STACK }}
          cloud-url: ${{ vars.CLOUD_URL }}
          work-dir: iac