name: Run Migration

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true
      DATABASE_URL:
        required: true

jobs:
  filter-migrate:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      migrate: ${{ steps.filter.outputs.migrate }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            migrate:
              - 'prisma/**'
              - '.github/workflows/migrate.yml'
  migrate:
    needs: [filter-migrate]
    if: needs.filter-migrate.outputs.migrate == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate with Google 🔑
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Download SQL Auth Proxy
        run: "wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy"

      - name: Make the Cloud SQL Auth proxy executable
        run: "chmod +x cloud_sql_proxy"

      - name: Prints instance
        run: echo "$INSTANCE"
        env:
          INSTANCE: ${{ vars.DATABASE_NAME }}

      - name: Start the Cloud SQL proxy
        run: ./cloud_sql_proxy -instances=$INSTANCE & sleep 5
        env:
          INSTANCE: ${{ vars.DATABASE_NAME }}

      - name: Run migration
        run: "npx prisma migrate deploy"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
