name: Migration trigger

on:
  push:
    branches: ["main"]
    paths:
      - "prisma/**"
      - '.github/**'
  pull_request:
    branches: ["main"]
    paths:
      - "prisma/**"
      - '.github/**'

jobs:
  migrate:
    uses: ./.github/workflows/migrate.yml
    with:
      environment: dev
    secrets: inherit
